[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.unit-tests]
command = "cargo"
args = ["test"]

[tasks.build]
run_task = { name = ["build-llm"] }

[tasks.release-build]
run_task = { name = ["release-build-llm"] }

[tasks.build-portable]
install_crate = "cargo-binstall"
run_task = { name = ["build-llm-portable"] }

[tasks.release-build-portable]
run_task = { name = ["release-build-llm-portable"] }

[tasks.wit]
run_task = { name = ["llm-wit"] }

[tasks.build-all]
script_runner = "@duckscript"
script = '''
mkdir components/debug

cm_run_task build
cm_run_task copy-debug-artifacts

cm_run_task build-portable
cm_run_task copy-debug-artifacts --portable
'''

[tasks.release-build-all]
script_runner = "@duckscript"
script = '''
mkdir components/release

cm_run_task set-version

cm_run_task clean
cm_run_task release-build
cm_run_task copy-release-artifacts

cm_run_task clean
cm_run_task release-build-portable
cm_run_task copy-release-artifacts --portable
'''

[tasks.build-test-components]
description = "Builds all test components with golem-cli"
run_task = { name = ["llm-build-test-components"] }

[tasks.copy-debug-artifacts]
script_runner = "@duckscript"
script = '''

is_portable = eq ${1} "--portable"

targets = array llm_openai llm_anthropic llm_grok llm_openrouter llm_ollama
for target in ${targets}
    if is_portable
        cp target/wasm32-wasip1/debug/golem_${target}.wasm components/debug/golem_${target}-portable.wasm
    else
        cp target/wasm32-wasip1/debug/golem_${target}.wasm components/debug/golem_${target}.wasm
    end
end
'''

[tasks.copy-release-artifacts]
script_runner = "@duckscript"
script = '''

is_portable = eq ${1} "--portable"

targets = array llm_openai llm_anthropic llm_grok llm_openrouter llm_ollama
for target in ${targets}
    if is_portable
        cp target/wasm32-wasip1/release/golem_${target}.wasm components/release/golem_${target}-portable.wasm
    else
        cp target/wasm32-wasip1/release/golem_${target}.wasm components/release/golem_${target}.wasm
    end
end
'''

# Tasks for llm module
[tasks.build-llm]
command = "cargo"
args = ["make", "--cwd", "llm", "build"]

[tasks.build-llm-portable]
command = "cargo"
args = ["make", "--cwd", "llm", "build-portable"]

[tasks.release-build-llm]
command = "cargo"
args = ["make", "--cwd", "llm", "build"]

[tasks.release-build-llm-portable]
command = "cargo"
args = ["make", "--cwd", "llm", "build-portable"]

[tasks.llm-wit]
command = "cargo"
args = ["make", "--cwd", "llm", "wit"]

[tasks.llm-build-test-components]
command = "cargo"
args = ["make", "--cwd", "llm", "build-test-components"]

# Maintenance tasks
[tasks.check]
description = "Runs rustfmt and clippy checks without applying any fix"
dependencies = ["check-clippy", "check-rustfmt"]

[tasks.check-rustfmt]
description = "Runs rustfmt checks without applying any fix"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check-clippy]
description = "Runs clippy checks without applying any fix"
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--", "--no-deps", "-Dwarnings"]

[tasks.fix]
description = "Runs rustfmt and clippy checks and applies fixes"
dependencies = ["wit", "fix-clippy", "fix-rustfmt"]

[tasks.fix-rustfmt]
description = "Runs rustfmt checks and applies fixes"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fix-clippy]
description = "Runs clippy checks and applies fixes"
install_crate = "clippy"
command = "cargo"
args = [
    "clippy",
    "--fix",
    "--allow-dirty",
    "--allow-staged",
    "--",
    "--no-deps",
    "-Dwarnings",
]

[tasks.set-version]
description = "Sets the version in all Cargo.toml files to the value of the VERSION environment variable"
condition = { env_set = ["VERSION"] }
script = '''
grep -rl --include 'Cargo.toml' '0\.0\.0' | xargs sed -i "s/0\.0\.0/${VERSION}/g"
'''

[tasks.set-version.mac]
condition = { env_set = ["VERSION"] }
script = '''
grep -rl --include '.*Cargo\.toml' '0\.0\.0' | xargs sed -i "" "s/0\.0\.0/${VERSION}/g"
'''

[tasks.set-version.windows]
script_runner = "powershell"
script_extension = "ps1"
condition = { env_set = ["VERSION"] }
script = '''
$cargoFiles = Get-ChildItem . Cargo.toml -rec
foreach ($file in $cargoFiles)
{
    (Get-Content $file.PSPath) |
    Foreach-Object { $_ -replace "0.0.0", $Env:VERSION } |
    Set-Content $file.PSPath
}
'''
