[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build-anthropic]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-anthropic"]

[tasks.build-grok]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-grok"]

[tasks.build-openai]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-openai"]

[tasks.build-openrouter]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-openrouter"]

[tasks.build]
dependencies = [
    "build-anthropic",
    "build-grok",
    "build-openai",
    "build-openrouter"
]

[tasks.release-build-anthropic]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-anthropic", "--release"]

[tasks.release-build-grok]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-grok", "--release"]

[tasks.release-build-openai]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-openai", "--release"]

[tasks.release-build-openrouter]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args=["build", "-p", "golem-llm-openrouter", "--release"]

[tasks.release-build]
dependencies = [
    "release-build-anthropic",
    "release-build-grok",
    "release-build-openai",
    "release-build-openrouter"
]

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]

#condition = { files_modified = { input = [
#    "wit/golem-llm.wit",
#    "wit/deps/wasi:io",
#], output = [
#    "llm/wit/deps/golem-llm/golem-llm.wit",
#    "llm-anthropic/wit/deps/golem-llm/golem-llm.wit",
#    "llm-grok/wit/deps/golem-llm/golem-llm.wit",
#    "llm-openai/wit/deps/golem-llm/golem-llm.wit",
#    "llm-openrouter/wit/deps/golem-llm/golem-llm.wit",
#] } }

script_runner = "@duckscript"
script = """
rm -r llm/wit/deps
mkdir llm/wit/deps/golem-llm
cp wit/golem-llm.wit llm/wit/deps/golem-llm/golem-llm.wit
cp wit/deps/wasi:io llm/wit/deps
rm -r llm-anthropic/wit/deps
mkdir llm-anthropic/wit/deps/golem-llm
cp wit/golem-llm.wit llm-anthropic/wit/deps/golem-llm/golem-llm.wit
cp wit/deps/wasi:io llm-anthropic/wit/deps
rm -r llm-grok/wit/deps
mkdir llm-grok/wit/deps/golem-llm
cp wit/golem-llm.wit llm-grok/wit/deps/golem-llm/golem-llm.wit
cp wit/deps/wasi:io llm-grok/wit/deps
rm -r llm-openai/wit/deps
mkdir llm-openai/wit/deps/golem-llm
cp wit/golem-llm.wit llm-openai/wit/deps/golem-llm/golem-llm.wit
cp wit/deps/wasi:io llm-openai/wit/deps
rm -r llm-openrouter/deps
mkdir llm-openrouter/wit/deps/golem-llm
cp wit/golem-llm.wit llm-openrouter/wit/deps/golem-llm/golem-llm.wit
cp wit/deps/wasi:io llm-openrouter/wit/deps
"""
