[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-google",
    "build-azure",
    "build-aws",
    "build-deepgram",
    "build-whisper",
] }

[tasks.build-portable]
run_task = { name = [
    "build-google-portable",
    "build-azure-portable",
    "build-aws-portable",
    "build-deepgram-portable",
    "build-whisper-portable",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-google",
    "release-build-azure",
    "release-build-aws",
    "release-build-deepgram",
    "release-build-whisper",
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-google-portable",
    "release-build-azure-portable",
    "release-build-aws-portable",
    "release-build-deepgram-portable",
    "release-build-whisper-portable",
] }

[tasks.build-google]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-google"]

[tasks.build-google-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-google", "--no-default-features"]

[tasks.build-azure]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-azure"]

[tasks.build-azure-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-azure", "--no-default-features"]

[tasks.build-aws]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-aws"]

[tasks.build-aws-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-aws", "--no-default-features"]

[tasks.build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram"]

[tasks.build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram", "--no-default-features"]

[tasks.build-whisper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper"]

[tasks.build-whisper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper", "--no-default-features"]

[tasks.release-build-google]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-google", "--release"]

[tasks.release-build-google-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-google", "--release", "--no-default-features"]

[tasks.release-build-azure]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-azure", "--release"]

[tasks.release-build-azure-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-azure", "--release", "--no-default-features"]

[tasks.release-build-aws]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-aws", "--release"]

[tasks.release-build-aws-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-aws", "--release", "--no-default-features"]

[tasks.release-build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram", "--release"]

[tasks.release-build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram", "--release", "--no-default-features"]

[tasks.release-build-whisper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper", "--release"]

[tasks.release-build-whisper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper", "--release", "--no-default-features"]

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]

script_runner = "@duckscript"
script = """
modules = array stt google azure aws deepgram whisper

for module in ${modules}
    rm -r ${module}/wit/deps
    mkdir ${module}/wit/deps/golem-stt
    cp wit/golem-stt.wit ${module}/wit/deps/golem-stt/golem-stt.wit
    cp wit/deps/io ${module}/wit/deps

    echo "Copied WIT for module stt::${module}"
end

# Copy WIT files for integration tests if test directory exists
if is_path_exists "../test/stt"
    rm -r ../test/stt/wit
    mkdir -p ../test/stt/wit/deps/golem-stt
    mkdir -p ../test/stt/wit/deps/io
    cp wit/golem-stt.wit ../test/stt/wit/deps/golem-stt/golem-stt.wit
    cp wit/deps/io/error.wit ../test/stt/wit/deps/io/error.wit
    cp wit/deps/io/poll.wit ../test/stt/wit/deps/io/poll.wit
    cp wit/deps/io/streams.wit ../test/stt/wit/deps/io/streams.wit
    cp wit/deps/io/world.wit ../test/stt/wit/deps/io/world.wit
    
    echo "Copied WIT for module test"
end
"""

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds stt test components with golem-cli"
script = '''
if [ -d "../test/stt" ]; then
    cd ../test/stt
    
    golem-cli --version
    golem-cli app clean
    golem-cli app build -b google-debug
    golem-cli app clean
    golem-cli app build -b azure-debug
    golem-cli app clean
    golem-cli app build -b aws-debug
    golem-cli app clean
    golem-cli app build -b deepgram-debug
    golem-cli app clean
    golem-cli app build -b whisper-debug
fi
'''